AMI:
  el-6-x86_64:
    :image: 
      :pe: ami-57db123e
      :foss: ami-57db123e
    :region: us-east-1
  el-6-i386:
    :image:
      :pe: ami-02f85a6b
      :foss: ami-02f85a6b
    :region: us-east-1
  el-5-i386:
    :image:
      :pe: ami-0bd16d62
      :foss: ami-0bd16d62
    :region: us-east-1
  ubuntu-10.04-i386:
    :image:
      :pe: ami-f5d76b9c
      :foss: ami-f5d76b9c
    :region: us-east-1
