AMI:
  amazon-6-x86_64:
    :image: 
      :pe: ami-9ae663f3
    :region: us-east-1
  amazon-6-i386:
    :image:
      :pe: ami-06e1646f
    :region: us-east-1
  el-6-x86_64:
    :image:
      :pe: ami-57db123e
      :foss: ami-57db123e
    :region: us-east-1

  el-6-x86_64-west:
    :image:
      :pe: ami-aa8b039a
      :foss: ami-aa8b039a
    :region: us-west-2

  el-5-x86_64-west:
    :image:
      :pe: ami-4433bf74
      :foss: ami-4433bf74
    :region: us-west-2

  ubuntu-10.04-amd64-west:
    :image:
      :pe: ami-52ea6262
      :foss: ami-52ea6262
    :region: us-west-2

  ubuntu-12.04-amd64-west:
    :image:
      :pe: ami-d6e860e6
      :foss: ami-d6e860e6
    :region: us-west-2

  debian6-amd64-west:
    :image:
      :pe: ami-4eea627e
      :foss: ami-4eea627e
    :region: us-west-2

  el-6-i386:
    :image:
      :pe: ami-02f85a6b
      :foss: ami-02f85a6b
    :region: us-east-1
  el-5-i386:
    :image:
      :pe: ami-0bd16d62
      :foss: ami-0bd16d62
    :region: us-east-1
  ubuntu-10.04-i386:
    :image:
      :pe: ami-f5d76b9c
      :foss: ami-f5d76b9c
    :region: us-east-1
